#!/usr/bin/env python3
"""Convert 32-bit binary machine code into a Quartus ROM MIF."""

from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_DEPTH = 1024
DEFAULT_WIDTH = 32
SELECTED_TEN_TESTS = (
    "01_soma_1_ate_n",
    "02_fatorial",
    "03_fibonacci",
    "04_numero_primo",
    "05_maior_elemento_vetor",
    "06_busca_linear_vetor",
    "07_bubble_sort",
    "08_mdc",
    "09_matriz_loops_aninhados",
    "10_carga_preempcao",
)


def read_machine_words(path: Path, width: int) -> list[str]:
    if not path.is_file():
        raise FileNotFoundError(
            f"machine-code input not found: {path}. Generate it first, for example with 'make run_selected_10'."
        )

    words: list[str] = []
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        word = raw_line.strip()
        if not word:
            continue
        if len(word) != width or any(bit not in "01" for bit in word):
            raise ValueError(f"{path}:{line_number}: expected one {width}-bit binary word")
        words.append(word)
    if not words:
        raise ValueError(f"machine-code input is empty: {path}")
    return words


def render_mif(words: list[str], *, depth: int, width: int) -> str:
    if len(words) > depth:
        raise ValueError(f"machine code has {len(words)} words, but the ROM depth is {depth}")

    lines = [
        "-- Generated by tools/generate_mif.py; do not edit by hand.",
        f"DEPTH = {depth};",
        f"WIDTH = {width};",
        "ADDRESS_RADIX = DEC;",
        "DATA_RADIX = BIN;",
        "",
        "CONTENT BEGIN",
    ]
    lines.extend(f"  {address} : {word};" for address, word in enumerate(words))
    if len(words) < depth:
        lines.append(f"  [{len(words)}..{depth - 1}] : {'0' * width};")
    lines.extend(("END;", ""))
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Convert binary machine-code words to a Quartus MIF.")
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument("--input", type=Path, help="Machine-code text file with one binary word per line.")
    input_group.add_argument(
        "--selected-ten-dir",
        type=Path,
        help="Directory containing the ten selected *_machine_code.txt files.",
    )
    parser.add_argument("--output", type=Path, help="Destination .mif file for --input mode.")
    parser.add_argument("--output-dir", type=Path, help="Destination directory for --selected-ten-dir mode.")
    parser.add_argument("--depth", type=int, default=DEFAULT_DEPTH, help="ROM depth in words (default: 1024).")
    parser.add_argument("--width", type=int, default=DEFAULT_WIDTH, help="Machine-word width in bits (default: 32).")
    return parser


def write_mif(words: list[str], output_path: Path, *, depth: int, width: int) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_mif(words, depth=depth, width=width), encoding="utf-8")


def generate_selected_ten_mifs(input_dir: Path, output_dir: Path, *, depth: int, width: int) -> None:
    for program_number, test_name in enumerate(SELECTED_TEN_TESTS, start=1):
        input_path = input_dir / f"{test_name}_machine_code.txt"
        output_path = output_dir / f"program{program_number}.mif"
        words = read_machine_words(input_path, width)
        write_mif(words, output_path, depth=depth, width=width)
        print(f"program{program_number}.mif <- {test_name} ({len(words)} machine words)")


def main() -> None:
    args = build_parser().parse_args()
    if args.depth <= 0 or args.width <= 0:
        raise SystemExit("--depth and --width must be positive")

    try:
        if args.input is not None:
            if args.output is None:
                raise ValueError("--output is required when using --input")
            words = read_machine_words(args.input, args.width)
            write_mif(words, args.output, depth=args.depth, width=args.width)
            print(f"Generated {args.output} with {len(words)} machine words and {args.depth - len(words)} zero-filled words.")
        else:
            if args.output_dir is None:
                raise ValueError("--output-dir is required when using --selected-ten-dir")
            generate_selected_ten_mifs(args.selected_ten_dir, args.output_dir, depth=args.depth, width=args.width)
    except (OSError, ValueError) as error:
        raise SystemExit(f"MIF generation failed: {error}") from error


if __name__ == "__main__":
    main()
